version: "1.0"
services:
  api:
    container_name: "nestjs-prisma"
    restart: always
    image: node:18-alpine
    env_file:
      - .env
    ports:
      - 3000:3000
      #Prisma Studio
      - 5555:5555
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    tty: true
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: PasswordO1.
    volumes:
      - nestjs-prisma:/var/opt/mssql
volumes:
  nestjs-prisma:
